---
- hosts: all
  become: true
  tasks:
  - name: install apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
    register: add_key

  - name: add docker repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
      state: present
      update_cache: yes

  - name: install docker
    apt:
      name: docker-ce

  - name: add docker goup
    user:
      name: "{{ ansible_user_id }}"
      append: yes
      groups: docker
