---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repos
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/apt_packages.yml
    - include: tasks/make_dirs.yml
    - include: tasks/install_android_udev_rules.yml
    - name: install sublimetext3
        shell: scripts/install_sublimetext3.sh
        notify: echo done

  - name: install docker apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
    register: add_key

  - name: add docker repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
      state: present
      update_cache: yes

  - name: install docker
    apt:
      name: docker-ce
      state: present

  - name: add user to docker group
    user:
      name: "{{ ansible_user_id }}"
      append: yes
      groups: docker

# Linking configs
    - name: link ackrc file
      file:
        src: ack/.ackrc
        dest: ~/.ackrc
        state: link

# Handlers section
# Tasks in handlers section are not called unless called by tasks

handlers:
    - name: echo done
        shell: echo 'DOne'

