---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repos
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/apt_packages.yml
    - include: tasks/make_dirs.yml
    - include: tasks/install_android_udev_rules.yml
