---
- name: Remove apt packages
  when: ansible_os_family == "Debian"
  apt:
    name: {{ item }}
    state: absent
  with_items:
    - k3b
    - pidgin
    - thunderbird
    - brasero
    - xplayer
    - gnome-orca
    - mono-runtime-common
    - ndiswrapper*

- name: Install apt packages
  become: yes
  apt:
    name: {{ item }}
    state: present
  with_items:
    - zip
    - git
    - vim
    - meld
    - build-essential
    - ack-grep
    - libssl-dev
    - htop
    - tree
    - curl
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - gnome-tweak-tool
    - vlc
    - ubuntu-restricted-extras
    - ack-grep
    - net-tools
