---
- name: install python packages
  when: ansible_os_family == "Debian"
  become: true

  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-dev
    - python-wheel
    - python-pip
    - python-setuptools
    - python3-setuptools
    - python3-wheel
    - python3-dev
    - python3-pip
