---
- name: copy 51-android.rules to /etc/udev/rules.d/
  copy:
    src: files/51-android.rules
    dest: /etc/udev/rules.d/51-android.rules
    owner: root
    group: root
    mode: a+r

- name: reload udev rules
  become: yes
  command: udevadm control --reload-rules
