---
- name: copy 51-android.rules to /etc/udev/rules.d/
  copy:
    src: files/51-android.rules
    dest: /etc/udev/rules.d/
    owner: root
    group: root
    mode: a+r

- name: restart udev
  become: yes
  command: udevadm control --reload-rules
  service:
    name: udev
    state: restarted
