---
- name: install python3 packages
  when: ansible_os_family == "Debian"
  apt:
    name: "{{items}}"
    state: present
  with_items:
    - python3-setuptools
    - python3-wheel
    - python3-dev
    - python3-pip
