---
- name: install python2 packages
  when: ansible_os_family == "Debian"
  apt:
    name: "{{items}}"
    state: present
  with_items:
    - python-dev
    - python-wheel
    - python-pip
    - python-setuptools
